config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cerfacs-globc/icclim:
      branch: master
      repo: https://github.com/cerfacs-globc/icclim
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cerfacs-globc/icclim git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-dandelion-chinchilla.sh
        container: qc.acc_messy-rose-markhor
  QC.Doc:
    repos:
      github.com/cerfacs-globc/icclim find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-persimmon-goat.sh
        container: qc.doc_geeky-razzmatazz-neanderthal
      github.com/cerfacs-globc/icclim git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-amaranth-angelfish.sh
        container: qc.doc_muggy-corn-eel
      github.com/cerfacs-globc/icclim markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-alizarin-blue.sh
        container: qc.doc_beady-sapphire-bulldog
      github.com/cerfacs-globc/icclim restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-persimmon-dog.sh
        container: qc.doc_lovely-lime-leopard
  QC.Lic:
    repos:
      github.com/cerfacs-globc/icclim licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-ivory-badger.sh
        container: qc.lic_sleazy-salmon-dugong
  QC.Sec:
    repos:
      github.com/cerfacs-globc/icclim bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-tan-jaguar.sh
        container: qc.sec_wheezy-ochre-mandrill
  QC.Sty:
    repos:
      github.com/cerfacs-globc/icclim flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-eggplant-frog.sh
        container: qc.sty_skimpy-gamboge-sheep
  QC.Uni:
    repos:
      github.com/cerfacs-globc/icclim pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-pear-swan.sh
        container: qc.uni_geeky-olive-gar
  QC.Ver:
    repos:
      github.com/cerfacs-globc/icclim get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-teal-wildebeest.sh
        container: qc.ver_woolly-asparagus-kiwi
timeout: 5400
